// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.HistoryView = (function(_super) {
    __extends(HistoryView, _super);

    function HistoryView() {
      return HistoryView.__super__.constructor.apply(this, arguments);
    }

    HistoryView.prototype.className = 'history';

    HistoryView.prototype.template = _.template('<h2>History</h2><ul></ul>');

    HistoryView.prototype.initialize = function() {
      this.collection.on('add remove change', (function(_this) {
        return function() {
          return _this.render();
        };
      })(this));
      return this.render();
    };

    HistoryView.prototype.render = function() {
      this.$el.children().detach();
      this.$el.html(this.template(this.collection));
      return this.$('ul').append(this.collection.map(function(round) {
        return new RoundView({
          model: round
        }).$el;
      }));
    };

    return HistoryView;

  })(Backbone.View);

}).call(this);
