// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.RoundView = (function(_super) {
    __extends(RoundView, _super);

    function RoundView() {
      return RoundView.__super__.constructor.apply(this, arguments);
    }

    RoundView.prototype.className = "round";

    RoundView.prototype.tagName = "li";

    RoundView.prototype.template = _.template('<b><%= round %></b> <%= winner %>');

    RoundView.prototype.initialize = function() {
      this.model.on('change', (function(_this) {
        return function() {
          return _this.render;
        };
      })(this));
      return this.render();
    };

    RoundView.prototype.render = function() {
      this.$el.children().detach().end().html;
      return this.$el.html(this.template(this.model.attributes));
    };

    return RoundView;

  })(Backbone.View);

}).call(this);
