// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Round = (function(_super) {
    __extends(Round, _super);

    function Round() {
      return Round.__super__.constructor.apply(this, arguments);
    }

    Round.prototype.initialize = function(params) {
      this.set({
        round: params.round,
        winner: params.winner
      });
      return console.log('Round Initialized');
    };

    return Round;

  })(Backbone.Model);

}).call(this);
