// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.History = (function(_super) {
    __extends(History, _super);

    function History() {
      return History.__super__.constructor.apply(this, arguments);
    }

    History.prototype.model = Round;

    History.prototype.initialize = function() {
      return console.log('History Initialized');
    };

    return History;

  })(Backbone.Collection);

}).call(this);
